### ISSUE TITLE
az login

### ISSUE THREAD

**Issue by ragsns** [jsturtevant/docker-azure-fundamentals-workshop#1]
In the last exercise (hands-on with registries), you may want to cover the az login first.

You have all the details in https://github.com/billpratt/docker-azure-workshop/blob/master/deploy-docker-swarm.md that may need to be pulled into this exercise.

Also, the az CLI is not optional if you ask them to try this exercise (I think you list it as optional in the instructions elsewhere).

**Comment by billpratt** [comment]
Thanks for pointing this out. I am updating that lab to run **az** commands in a Docker container so it will not be necessary to install.

**Comment by jsturtevant** [comment]
Thanks! Added a step to run using docker container.  I will update to link to the login flow.

Did you go through the labs?  did they work other than that?  Appreciate any other feedback.
